import MainLayout from "@/components/MainLayout";
import "./globals.css";
import ProtectedRoute from "@/components/ProtectedRoute";

export const metadata = {
  title: "My Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ProtectedRoute>
      <MainLayout>
        {children}
      </MainLayout>
    </ProtectedRoute>
  );
}