import MainLayout from "@/components/MainLayout";
import "./globals.css";
import ProtectedRoute from "@/components/ProtectedRoute";
import useThemeStore from "@/stores/theme";
import ThemeToggle from "@/components/ThemeToggle";

export const metadata = {
  title: "My Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <ThemeToggle>
      <ProtectedRoute>
        <MainLayout>
          {children}
        </MainLayout>
      </ProtectedRoute>
    </ThemeToggle>
  );
}